### ISSUE TITLE
Inhalt: Komplexitätstheorie, vor allem NP-Vollständigkeitsbeweise

### ISSUE THREAD

**Issue by chuyang-wang-dev** [bwinf-guide/bwinf-guide#11]

**Comment by chuyang-wang-dev** [comment]
idk #14 hat NP Vollständigkeit noch nicht erfasst? Sollen wir es erstmal lassen oder machst du später noch ne PR?

**Comment by phgilde** [comment]
ich mache später noch mehr. ein beispiel für eine reduktion wäre auch noch gut, aber ich bin noch nicht sicher welches problem sich dafür am besten eignet. die reduktion sollte möglichst einfach sein, bloß um das prinzip zu zeigen.
dafür fallen mir ein:
hamiltonpath auf TSP reduzieren
CNF-SAT auf 3-SAT reduzieren
VERTEX-COVER auf SET-COVERING reduzieren

**Comment by phgilde** [comment]
Fehlt jetzt noch etwas in dem Artikel? Sonst würde ich schließen
