### ISSUE TITLE
Tipps zur 1. und 2. Runde

### ISSUE THREAD

**Issue by chuyang-wang-dev** [bwinf-guide/bwinf-guide#3]
- [x] 1. Runde
- [ ] 2. Runde
- erläuterung von sinnvollen erweiterungen für bonuspunkte

**Comment by Entjic** [comment]
Ich bin ein wenig verwirrt was die Struktur angeht. Wo ist das angedacht? Vermutlich könnte man das in "allgemeine Tipps" (gibt es das nicht schon irgendwo?) und Unterkategorien "Tipps zur 1. Runde" "Tipps zur 2. Runde" aufteilen.

![Image](https://github.com/bwinf-guide/bwinf-guide/assets/52130476/92e42523-b04e-443b-b8c4-8304ef22811e)

Hier irgendwo? 

Zudem stellt sich die Frage wie ausführlich das ganze angedacht ist.  Geht es lediglich um Tipps bezüglich Rahmenbedingungen und Formalitäten (sowas wie "in der zweiten Runde ist es zwingend notwendig Gedanken zur Komplexitätsbetrachtung in seiner Doku zu haben" oder "hey, die zweite Runde wird deutlich mehr Aufwand als die erste, plan deutlich mehr Zeit ein"), oder auch wirklich um inhaltliche Hilfen (bspw "wie Suche ich nach wissenschaftlichen Papers zu meinem Problem")?

**Comment by chuyang-wang-dev** [comment]
Zu 1. : 
Die Struktur ist zurzeit BWINF > Tipps > Runde 1 usw. Ist das nicht so in Unterkategorien aufgeteilt? Oder meinst du was anderes?
![image](https://github.com/bwinf-guide/bwinf-guide/assets/147445093/b2d16cb7-240f-4455-ae66-7203da159ce6)

Zu 2. : 
Jedenfalls sollten da lieber Stichpunkte vorkommen als große Abschnitte - Themen sollen in eigenen Abschnitten erklärt werden, in Tipps sollte man nur darauf verweisen. 

 "in der zweiten Runde ist es zwingend notwendig Gedanken zur Komplexitätsbetrachtung in seiner Doku zu haben" bzw."hey, die zweite Runde wird deutlich mehr Aufwand als die erste, plan deutlich mehr Zeit ein" passen gut hier rein, 

"wie Suche ich nach wissenschaftlichen Papers zu meinem Problem" soll einen eigenen Abschnitt bekommen und in zB. Runde 2 soll darauf hingewiesen werden

**Comment by Servant-of-the-Lord** [comment]
Ich denke mal das geplant ist noch Tips 2. Runde hinzuzufügen. Ob es wirklich sinnvoll ist allgemeine Tips zu haben denk ich nicht. 

Bezüglich des Rahmens: Ich alle genannten Punkte sollten enthalten sein jedoch nicht von Anfang. Wir können im Laufe der Zeit noch weitere hinzufügen.

**Comment by Tobotis** [comment]
Sollten wir es vielleicht so machen, dass man nicht den Tab "BWINF" hat, sondern schon spezifische Sachen? weil im Prinzip ist die ganze Seite ja für den BWINF...

**Comment by chuyang-wang-dev** [comment]
> Sollten wir es vielleicht so machen, dass man nicht den Tab "BWINF" hat, sondern schon spezifische Sachen? weil im Prinzip ist die ganze Seite ja für den BWINF...

ja, also zurzeit ist es unterteilt in Allgemeines (wofür steht die Guide), BWINF (alles inhaltliche Themen), Über uns (quasi Impressum, kann aber auch einfach weg von dem Top-Nav) und Themen (? wofür eigtl? Wir haben doch schon Suchen-Option. Ich meine es ist ja ne Übersicht, schlecht ist es definitiv nicht, aber idk). 

Das Problem ist dass die inhaltlichen Themen sehr viel werden können und wir nicht alles auf Top Nav packen können, deshalb muss man halt schauen. 

Ansonsten wäre vielleicht Allgemeines, Algorithmen, Theoretische Informatik und Tipps als Top Nav möglich. Gibt´s weitere Oberthemen?

**Comment by Tobotis** [comment]
"Themen" könnten vielleicht eine Übersicht auf der main page sein, also wenn man etwas runterscrollt... damit man quasi die Themen schnell accessen kann.
Ansonsten würde ich vielleicht in die Top-Nav: sowas wie "Allgemein" und "Inhalt" machen, mehr nicht oder?

**Comment by chuyang-wang-dev** [comment]
lets say it's done for now
